### ISSUE TITLE
Is it possible to stream a video?

### ISSUE THREAD

**Issue by dentuzhik** [tushariscoolster/alfred-youtube-vlc-workflow#1]
Hey there!

Thanks for a nice workflow. Do you think it is possible to stream a video to VLC using this?

**Comment by tushar-borole** [comment]
@dentuzhik  i created this plugin to listen just son, but you can do small tweak in plugin to make it work

**Comment by dentuzhik** [comment]
Can you point me out to the place in the code which requires a tweak? Would be happy to try to help with that.

**Comment by tushar-borole** [comment]
in script
`open -a /Applications/VLC.app "$query" --args --no-video --loop --no-osd --no-macosx-nativefullscreenmode --video-wallpaper `

remove --no-video

**Comment by dentuzhik** [comment]
Thanks a lot!
